// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLW68OKBUzSfLVOVMOElc3SWrmcoBtkm8',
    appId: '1:525387087898:web:61566aa14c56a8d89691a3',
    messagingSenderId: '525387087898',
    projectId: 'todo-app-60221',
    authDomain: 'todo-app-60221.firebaseapp.com',
    storageBucket: 'todo-app-60221.appspot.com',
    measurementId: 'G-7Z0QDLFHBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6sldQ48Y0ifipCqnnjqbUzr7fB10TGA',
    appId: '1:525387087898:android:7bde0726157a42409691a3',
    messagingSenderId: '525387087898',
    projectId: 'todo-app-60221',
    storageBucket: 'todo-app-60221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XoyL6ISqkGX88teSwdCJsKF5Yl-5NPE',
    appId: '1:525387087898:ios:d18df00f997fffc89691a3',
    messagingSenderId: '525387087898',
    projectId: 'todo-app-60221',
    storageBucket: 'todo-app-60221.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XoyL6ISqkGX88teSwdCJsKF5Yl-5NPE',
    appId: '1:525387087898:ios:6660c832378c4f2b9691a3',
    messagingSenderId: '525387087898',
    projectId: 'todo-app-60221',
    storageBucket: 'todo-app-60221.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
